CREATE TABLE IF NOT EXISTS activities (
  id INT AUTO_INCREMENT PRIMARY KEY,
  slug VARCHAR(128) NOT NULL,
  title VARCHAR(120) NOT NULL,
  category VARCHAR(64) NOT NULL DEFAULT '',
  frequency VARCHAR(64) NOT NULL DEFAULT '',
  duration VARCHAR(64) NOT NULL DEFAULT '',
  difficulty VARCHAR(32) NOT NULL DEFAULT '',
  scene VARCHAR(128) NOT NULL DEFAULT '',
  summary TEXT,
  tagline VARCHAR(255) NOT NULL DEFAULT '',
  description TEXT,
  highlights_json LONGTEXT,
  steps_json LONGTEXT,
  tips_json LONGTEXT,
  cover_image LONGTEXT,
  sort_order INT NOT NULL DEFAULT 0,
  status ENUM('pending', 'approved', 'rejected') NOT NULL DEFAULT 'approved',
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_by INT NULL DEFAULT NULL,
  reviewed_by INT NULL DEFAULT NULL,
  reviewed_at DATETIME NULL DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_slug (slug),
  KEY idx_active_sort (is_active, sort_order, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
